"""migrate4

Revision ID: 11718564f6cb
Revises: 9885962a29d8
Create Date: 2023-04-12 11:37:25.217803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11718564f6cb'
down_revision = '9885962a29d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
